### PR TITLE
Display work item link using AzDevops API

### PR DESCRIPTION
**Pull request by AltarBeastiful**
I'm well advanced in fixing #72, but I'm stuck on rendering differences between wkhtmltopdf and chrome/firefox. I guess it"s because they still use QT 4.

This is the html generated displayed in chrome : 
image
And this is how it's printed in the pdf : 
image

The border is all around the element and text color is blue for some reason. State color could be ignored, as Azure Devops already ignores it when printing a single page to PDF.

Also, we should maybe create a PAT to your devops organization to allow testing of this feature in CI.

- [x] Fix rendering issues
- [ ] Create a read only PAT to https://dev.azure.com/mmelcher
- [ ] Add rendering in test.html

### CODE REVIEW

**Comment by MaxMelcher** [comment]
I'll check once I am back from vacation next week. 

Rendering/styling is a pain, I would love to switch to something better - but most of the options are commercial.

**Comment by MaxMelcher** [comment]
I'll check once I am back from vacation next week. 

Rendering/styling is a pain, I would love to switch to something better - but most of the options are commercial.

**Comment by AltarBeastiful** [comment]
Checking wkhtmltopdf site you can see it's not likely to improve: https://wkhtmltopdf.org/status.html

I think moving to puppeteer for pdf printing is the best course of action. In the meantime, we could just delay this PR or merge with minor css fixes. Might be smarter to invest time in switching to puppeteer than trying to work around wkhtmltopdf.

Enjoy the vacation !

**Comment by MaxMelcher** [comment]
Puppeteer is already added, would simplify the three external cases also (mermaid, latex, code highlighter) - and reduce the binary size. Potentially would work in Linux, too.

Thanks for the pointer - I totally agree this would be a better path and will result in a v4 :)
You wanna start?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by MaxMelcher** [comment]
I released a draft version: https://github.com/MaxMelcher/AzureDevOps.WikiPDFExport/releases/tag/4.0.0-alpha

**Comment by AltarBeastiful** [comment]
Nice work on puppeteer !

In the mean time I almost fixed the rendering issues I had :
* Removed uses of `var` as it's css 3
* Fixed some margins and line height

Still have a problem with using border-radius to round corners of the left colored border. 
I commented it as it looks better without it. I also opened an issue at wkhtmltopdf/wkhtmltopdf#5068

image

**Comment by MaxMelcher** [comment]
If I add a PAT to the launch.json it gets immediately discovered by azure devops and revoked within 72hours. Security :)

**Pull request merged**
