### PR TITLE
Added support for header-url and header-line

### PR DESCRIPTION
**Pull request by roel4ez**
header-url does not work in combination with header-right/header-left/header-center #6

### CODE REVIEW

**Comment by roel4ez** [comment]
I notice now that the default behavior has changed: the header-line is always `visible` in the current version. This PR changes the behavior to having it `hidden` if the argument is not provided. 

I will update the PR.

**Comment by roel4ez** [comment]
Don't merge yet, I also see that the footer is no longer displayed when using header-url

**Comment by roel4ez** [comment]
I added support for `footer-url`. It seems that wkhtmltopdf does not like a mix of `footer-*` and `header-*` with `footer-url` and `header-url`.

I also added an example in the root on how such a header and footer could look like. (footer from https://wkhtmltopdf.org/usage/wkhtmltopdf.txt)
Please let me know if you want to have more extended examples, or if I should put them in a `/samples` folder instead.

**Comment by roel4ez** [comment]
you can merge the PR whenever you're ready @MaxMelcher

**Comment by MaxMelcher** [comment]
Merged and released. Thank you @roel4ez - I tested the header-example and I like the cat picture :)

**Pull request merged**
