### PR TITLE
Syntax hightlight code in code block using hightlight.js

### LINKED ISSUE #73: Colorize code blocks
Code blocks seem to be properly styled using `<code class="language-xxx">` but not color are shown in the final PDF.
Also the code block could be more outlined like the azure devops wiki style :
image

### PR DESCRIPTION
**Pull request by AltarBeastiful**
Fixes #73

### CODE REVIEW

**Comment by AltarBeastiful** [comment]
Looks good in HTML :
image

But in PDF there is too much padding around the code: 
image

Any idea why that's happening ?

**Comment by AltarBeastiful** [comment]
Fixed it by removing the border from `pre` only when using default hightlight style. I could also always remove it but I feel it could startle users.

**Comment by Jheronymus** [comment]
since the tool allows for building with a specific style sheet, we should limit 'build-in' styling as much as possible.
in the devopswikistyle.css the pre-tag has border-radius: 2px and padding: 15px.
This is exactly how its displayed in the devops wiki.
With the information given I can't see why you get so much padding

**Comment by MaxMelcher** [comment]
Cool, thanks for the PR - trying to release it later today!

**Pull request merged**
