### PR TITLE
#71 - TOC feature from MarkdigToc

### PR DESCRIPTION
**Pull request by chrPetry**
Added basic toc feature and enhanced the idea by merging md files into a single one for a single TOC.
Perhaps you have a better idea for this use case.

### CODE REVIEW

**Comment by chrPetry** [comment]
Better would be to fetch all the headers (h1, h2..)  at the beginning.
But I think then the linking would break, am I right?

**Comment by chrPetry** [comment]
Ok I just switched to fetching first all headers.
Added also some unit tests

Works very well for me!

**Comment by MaxMelcher** [comment]
Cool stuff, thanks a lot! I need a weekend or two to do some testing and then we can ship it!

**Comment by chrPetry** [comment]
Thank **you** for this nice work and nice coding style 👍

**Comment by MaxMelcher** [comment]
just released - thank you so much @chrPetry!

**Comment by chrPetry** [comment]
:) happy to contribute.

**Pull request merged**
